"""Refit repeatedly, and never let a model trade a day it has seen.

A single train/test split answers one question badly. It says how a
strategy fitted on one arbitrary period did on one other arbitrary
period, and the answer moves a great deal with where the cut was made —
slide it six months and a discovery becomes a dud, which is a fact about
the cut and not about the strategy. Walk-forward refits repeatedly and
always trades forward, so every reported trade was generated by a model
that had not seen the day it traded.

Training expands and never rolls. Each refit sees ALL history to that
point, because the alternative — a fixed-length window sliding forward —
quietly drops 2008 out of the training set somewhere around 2018, and a
model refitted in 2022 on a rolling ten years has never been shown a
credit crisis. The sample was chosen to contain the episodes that break
things; a window that discards them gives that back.

The trap this file exists to close is subtler than lookahead, and it is
why the result object is shaped the way it is. A walk-forward produces
two curves per fold — the one the model was fitted on and the one it
traded blind — and they sit one attribute apart. Nothing stops somebody
computing a Sharpe on the wrong one, and the wrong one is always the
better-looking. So there is exactly one stitched curve on the result,
`oos_equity`, assembled only from days each model traded blind; the
fitted curves live behind `in_sample_curves()`, are never stitched, and
`result.equity` raises rather than resolving to something plausible.

They are never stitched for a reason worth stating once. Under expanding
training the in-sample windows OVERLAP — every fold's training set
contains every earlier fold's — so a "continuous in-sample curve" would
compound 2008 once for each refit that had seen it. There is no such
series. Returning the folds separately makes it impossible to build one
by accident.

Two other things this module insists on.

**It never imports a strategy.** Fitting and running arrive as
callables, which is what makes the whole thing testable with a stub that
returns a constant, and what stops the validation layer growing opinions
about what a strategy is.

**Every configuration evaluated is written to `metrics.TrialCounter`.**
A walk-forward that tries five parameter sets at each of fifteen refits
has searched five configurations, not one, and the naive count a reader
would assume — "we ran one backtest" — understates the search by the
whole factor that the deflated Sharpe exists to correct for. A `fit` that
returns a bare mapping is taken at its word as one configuration; a `fit`
that searched and wants to say so returns a `FitOutcome` carrying every
candidate it looked at.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any, Callable, Mapping, Sequence

import numpy as np
import pandas as pd

from ..engine import metrics

__all__ = [
    "FitOutcome",
    "Fold",
    "FoldResult",
    "WalkForward",
    "WalkForwardError",
    "WalkForwardResult",
    "Window",
]


class WalkForwardError(ValueError):
    """The schedule, the callables or a returned curve is malformed."""


#: Refits happen at most once a year, and the reason is a prior rather
#: than something measured. A strategy refitted monthly is fitted to
#: noise: twelve times a year it re-estimates from mostly the same
#: history plus one month of new tape, and the parameter it picks tracks
#: that month. The second reason is the worse one — the cadence is
#: itself a parameter, and a cadence chosen by seeing which one
#: backtested best is a fitted parameter that owes the deflated Sharpe a
#: trial like any other. So the floor is stated here, before any result
#: exists, and `refit_frequency` goes into every trial's config hash so
#: that changing it starts a new search rather than continuing an old one
#: under the same N.
MIN_REFIT_FREQUENCY_YEARS = 1

#: A guard against the unit that everybody reaches for. `refit_frequency`
#: is in YEARS; a 12 here is twelve years, not twelve months, and the
#: schedule it produces would look like a bug in the data rather than a
#: bug in the call.
MAX_REFIT_FREQUENCY_YEARS = 10

#: A tail shorter than a calendar quarter is absorbed into the fold
#: before it rather than earning a refit of its own. A model refitted to
#: govern three weeks of trading has not been tested by those three
#: weeks, and it would sit in the drift table carrying the same weight as
#: one that governed a year. A quarter rather than some other floor
#: because it is the shortest window `metrics.REPORT_PERIODS` is willing
#: to name — 2018Q4, about sixty-four sessions — and a period the report
#: will not describe on its own is not a period worth refitting for.
#:
#: Deliberately absolute rather than a fraction of the cadence. A
#: fraction sounds tidier and quietly absorbs a whole year of real
#: out-of-sample trading under a biennial cadence, which is a year of
#: evidence thrown away to avoid an untidy last row.
MIN_TAIL_DAYS = 92

#: A run may hand back a few bars of lead-in before its test window, and
#: the last of them becomes the anchor the fold's returns are measured
#: from. More than a week of it means the run ignored the window it was
#: given, which is the failure this bound is here to name.
MAX_LEAD_IN_SESSIONS = 5

#: The longest stretch of a fold's test window that may pass with no
#: session reported before the walk calls it a hole rather than a
#: holiday. Ten calendar days: the widest ordinary gap between NYSE
#: sessions is four (a holiday Monday behind a weekend) and the widest
#: since 1995 is seven (the week of 11 September 2001), so ten clears
#: both and is still about a ninth of the shortest test window this
#: schedule will build.
#:
#: The number is the easy part. The policy it enforces is that **a run
#: which stops emitting NAV has stopped REPORTING, and that is an error
#: rather than a result.** Going flat is a POSITION: a book in cash
#: still has a NAV, still prints it every session, and still hands back
#: a curve of zero returns that stitches like any other. Silence is a
#: different event, and at this layer it is indistinguishable from a run
#: that crashed, a panel that ran out early, or a loop that broke on the
#: first exception — none of which anybody would knowingly report a
#: Sharpe over. Every headline number in the project is computed on the
#: stitched curve, so a fold that quietly returns January of a year the
#: report calls out-of-sample makes T smaller than the period named
#: beside it, with nothing anywhere saying so.
#:
#: Hence: truncation raises, and there is deliberately no argument to
#: switch it off. A flag that suppresses a completeness check is set
#: once, in a hurry, by somebody certain this fold is the exception, and
#: never unset — and the curve it admits carries no mark saying it is
#: short. Both legitimate cases have honest fixes that are not a flag: a
#: strategy holding nothing emits the flat level, and a panel that ends
#: before the schedule does means the schedule's `end` is wrong and
#: belongs moved back, where it enters the config hash and the reader
#: can see it.
MAX_UNREPORTED_DAYS = 10

#: Drift thresholds for the parameter table. Both are priors, neither
#: was chosen by seeing which one flagged the strategies we disliked, and
#: neither gates anything — they colour a diagnostic column and nothing
#: else. A parameter that changes at more than half the refits is
#: chasing; a numeric parameter whose largest choice is more than three
#: times its smallest was never really one parameter.
UNSTABLE_CHURN = 0.5
UNSTABLE_SPREAD = 3.0


# -- windows ------------------------------------------------------------


@dataclass(frozen=True)
class Window:
    """A closed date range, `[start, end]`, both ends INCLUSIVE.

    Inclusive because that is what `.loc[start:end]` does on a pandas
    DatetimeIndex, and a half-open convention here would mean every
    caller writing the off-by-one themselves — on the boundary between a
    training set and the first day it is asked to trade, which is
    precisely the boundary that must not blur.
    """

    start: pd.Timestamp
    end: pd.Timestamp

    def __post_init__(self) -> None:
        object.__setattr__(self, "start", _timestamp(self.start))
        object.__setattr__(self, "end", _timestamp(self.end))
        if self.end < self.start:
            raise WalkForwardError(f"window ends {self.end.date()} before it starts")

    @property
    def days(self) -> int:
        return int((self.end - self.start).days) + 1

    @property
    def years(self) -> float:
        return self.days / metrics.DAYS_PER_YEAR

    def contains(self, when: Any) -> bool:
        ts = _timestamp(when)
        return self.start <= ts <= self.end

    def slice(self, obj: pd.Series | pd.DataFrame) -> pd.Series | pd.DataFrame:
        """Cut a date-indexed object to this window.

        Offered so that a `fit` never has to write the cut itself. The
        module cannot stop a fit function reaching around this and
        reading the whole panel — nothing can, short of handing it a
        truncated panel the way `MarketView` does — but every extra place
        a caller writes `df.loc[a:b]` by hand is another place the b is
        wrong by a day.
        """
        if not isinstance(obj.index, pd.DatetimeIndex):
            raise WalkForwardError("can only slice something indexed by date")
        return obj.loc[self.start : self.end]

    def __str__(self) -> str:
        return f"{self.start.date()}..{self.end.date()}"


@dataclass(frozen=True)
class Fold:
    """One refit and the stretch of tape it was then asked to trade.

    `train.end` is the day before `test.start`, always. The gap is not a
    purge — this is a daily-decision, next-open-fill engine, so one day
    of separation is the whole of the leakage a label could carry — but
    it is stated in the type rather than assumed, because the two
    windows touching is how a training set ends up containing its own
    first test day.
    """

    index: int
    refit_on: pd.Timestamp
    train: Window
    test: Window

    def __post_init__(self) -> None:
        if self.train.end >= self.test.start:
            raise WalkForwardError(
                f"fold {self.index}: training runs to {self.train.end.date()} "
                f"and testing opens {self.test.start.date()} — the model would "
                "be fitted on a day it is about to trade"
            )


# -- what a fit hands back ----------------------------------------------


@dataclass(frozen=True)
class FitOutcome:
    """The parameters chosen at a refit, and everything considered.

    `evaluated` is the honest part. A fit function that sweeps a grid and
    returns only its winner has hidden the sweep from the trial ledger,
    and the deflated Sharpe then deflates against a search of one. Listing
    the candidates costs nothing and is the difference between an N a
    reader can check and an N we asserted.

    `chosen` is added to `evaluated` if it is not already there. A
    configuration good enough to trade was evaluated by definition.
    """

    chosen: Mapping[str, Any]
    evaluated: tuple[Mapping[str, Any], ...] = ()
    note: str = ""

    def __post_init__(self) -> None:
        chosen = dict(self.chosen)
        seen = [dict(c) for c in self.evaluated]
        key = metrics.TrialCounter.hash_config(chosen)
        if all(metrics.TrialCounter.hash_config(c) != key for c in seen):
            seen.append(chosen)
        object.__setattr__(self, "chosen", chosen)
        object.__setattr__(self, "evaluated", tuple(seen))


FitFn = Callable[[Window], "Mapping[str, Any] | FitOutcome"]
RunFn = Callable[[Mapping[str, Any], Window], Any]


# -- per-fold and whole-run results --------------------------------------
#
# Both result types are `eq=False`. They carry pandas objects, and a
# generated `__eq__` compares field tuples element-wise and then asks for
# the truth value of the resulting array — so `a == b` raises rather than
# answering. Identity is the honest comparison for a run anyway.


@dataclass(frozen=True, eq=False)
class FoldResult:
    """What one refit chose, and what it then earned trading blind.

    `oos_returns` rather than a curve, because the curve is only
    meaningful once it has been chained onto everything before it. The
    fold's own NAV series is kept in `raw_curve` for anyone reconciling a
    single fold against a single backtest, and it is deliberately not the
    thing any statistic is computed from.
    """

    index: int
    refit_on: pd.Timestamp
    train: Window
    test: Window
    parameters: Mapping[str, Any]
    evaluated: tuple[Mapping[str, Any], ...]
    note: str
    raw_curve: pd.Series = field(repr=False)
    oos_returns: pd.Series = field(repr=False)
    #: The session spent as this fold's anchor and therefore absent from
    #: the stitched curve. One per seam, unless the run handed back a
    #: lead-in bar to serve as the anchor instead.
    anchor_session_dropped: bool = False
    #: The widest run of calendar days inside the test window for which
    #: the run reported no session at all. Weekends and holidays put a
    #: two or a three here on a perfectly healthy fold; anything past
    #: MAX_UNREPORTED_DAYS raised rather than reaching this object. It is
    #: carried so a gap under the tolerance is still a printed number
    #: rather than something a reader would have to go looking for.
    unreported_days: int = 0

    @property
    def sessions(self) -> int:
        return int(len(self.oos_returns))


#: Attribute names somebody will reach for on the result, and the reason
#: each one is not there. An AttributeError with a sentence beats an
#: AttributeError with a repr, and it beats by a mile an alias that
#: silently resolves to whichever curve happened to be handy.
_TEMPTING_ATTRIBUTES: dict[str, str] = {
    "equity": (
        "there is no `equity` on a walk-forward result. The only curve any "
        "headline number may be computed from is `oos_equity`, which is "
        "stitched from days each model traded without having seen them. "
        "Fitted curves are per-fold and behind in_sample_curves()."
    ),
    "nav": "no `nav` here — see `oos_equity`.",
    "curve": "no `curve` here — see `oos_equity`.",
    "returns": "no `returns` here — take them from `oos_equity`.",
    "in_sample_equity": (
        "there is no single in-sample curve, and the absence is the point: "
        "expanding training windows overlap, so stitching them would compound "
        "the early years once per refit. Use in_sample_curves(), which returns "
        "them separately."
    ),
}


@dataclass(frozen=True, eq=False)
class WalkForwardResult:
    """One continuous out-of-sample curve, and the audit behind it."""

    label: str
    schedule: "WalkForward"
    folds: tuple[FoldResult, ...]
    #: THE object. Every reported statistic comes from this and nothing
    #: else. Each point was produced by a model fitted strictly before it.
    oos_equity: pd.Series = field(repr=False)
    trials_recorded: int = 0
    configs_evaluated: int = 0
    seam_sessions_dropped: int = 0
    _counter: metrics.TrialCounter | None = field(default=None, repr=False)
    _in_sample: Mapping[int, pd.Series] | None = field(default=None, repr=False)

    # -- the accessor that has to be asked for --------------------------

    def in_sample_curves(self) -> dict[int, pd.Series]:
        """Fitted curves, one per fold, never stitched.

        Raises if the run was not asked for them, rather than returning
        an empty dict — an empty result here reads as "the strategy made
        nothing in-sample", which is the opposite of "nobody looked".
        """
        if self._in_sample is None:
            raise WalkForwardError(
                "in-sample curves were not produced; pass "
                "include_in_sample=True to WalkForward.run if you want them. "
                "They are a diagnostic — no headline number may come from "
                "them, and they are per-fold because expanding training "
                "windows overlap and cannot be concatenated into a series."
            )
        return dict(self._in_sample)

    def __getattr__(self, name: str) -> Any:
        why = _TEMPTING_ATTRIBUTES.get(name)
        if why is not None:
            raise AttributeError(why)
        raise AttributeError(
            f"{type(self).__name__!r} object has no attribute {name!r}"
        )

    # -- the drift record -----------------------------------------------

    def parameters(self) -> pd.DataFrame:
        """One row per refit: the window, and what was chosen on it.

        Read this before the equity curve. A stitched curve says what the
        process earned; this says whether it was one process or fifteen
        wearing the same name.
        """
        rows: list[dict[str, Any]] = []
        for f in self.folds:
            row: dict[str, Any] = {
                "fold": f.index,
                "refit_on": f.refit_on,
                "train_start": f.train.start,
                "train_end": f.train.end,
                "train_years": f.train.years,
                "test_start": f.test.start,
                "test_end": f.test.end,
                "oos_sessions": f.sessions,
                "configs_evaluated": len(f.evaluated),
            }
            # Namespaced, because a strategy is entirely within its rights
            # to have a parameter called "fold" and it must not land on
            # top of the column that says which one this is.
            for key, value in f.parameters.items():
                row[f"param.{key}"] = value
            rows.append(row)
        return pd.DataFrame(rows)

    def parameter_drift(self) -> pd.DataFrame:
        """How much each chosen parameter moved between refits.

        A strategy whose lookback swings from 20 to 200 and back is
        unstable whatever the stitched curve says: the curve is then the
        average of several different strategies, and the one that will
        run next year is whichever the last refit happened to land on.
        Nothing here gates anything — the column is called `unstable` and
        not `fail` on purpose, because the judgement is a person's.
        """
        frame = self.parameters()
        n = len(frame)
        rows: list[dict[str, Any]] = []
        for column in [c for c in frame.columns if c.startswith("param.")]:
            values = list(frame[column])
            keys = [_stable_key(v) for v in values]
            changes = sum(1 for a, b in zip(keys, keys[1:]) if a != b)
            churn = changes / (n - 1) if n > 1 else float("nan")
            numbers = [v for v in values if _is_number(v)]
            numeric = len(numbers) == len(values) and bool(values)
            lo = float(min(numbers)) if numeric else float("nan")
            hi = float(max(numbers)) if numeric else float("nan")
            spread = hi / lo if numeric and lo > 0 else float("nan")
            unstable = bool(
                (n > 1 and churn > UNSTABLE_CHURN)
                or (numeric and np.isfinite(spread) and spread > UNSTABLE_SPREAD)
            )
            rows.append(
                {
                    "parameter": column.removeprefix("param."),
                    "refits": n,
                    "distinct": len(set(keys)),
                    "changes": changes,
                    "churn": churn,
                    "min": lo,
                    "max": hi,
                    "spread": spread,
                    "first": values[0] if values else None,
                    "last": values[-1] if values else None,
                    "unstable": unstable,
                    "note": _drift_note(values, keys, changes, n, spread, unstable),
                }
            )
        if not rows:
            return pd.DataFrame(
                {
                    "parameter": pd.Series([], dtype="str"),
                    "refits": pd.Series([], dtype="int64"),
                    "distinct": pd.Series([], dtype="int64"),
                    "changes": pd.Series([], dtype="int64"),
                    "churn": pd.Series([], dtype="float64"),
                    "min": pd.Series([], dtype="float64"),
                    "max": pd.Series([], dtype="float64"),
                    "spread": pd.Series([], dtype="float64"),
                    "first": pd.Series([], dtype="object"),
                    "last": pd.Series([], dtype="object"),
                    "unstable": pd.Series([], dtype="bool"),
                    "note": pd.Series([], dtype="str"),
                }
            )
        return pd.DataFrame(rows)

    def coverage(self) -> pd.DataFrame:
        """Which sessions each fold contributed, so the seams are visible.

        `anchor_dropped` is the one to read. A fold whose run handed back
        no lead-in bar spends its first session as the anchor its returns
        are measured from, and that session is therefore absent from the
        stitched curve. One a year is small; it is not nothing, and a
        number that is quietly missing from T is exactly the sort of
        thing that should be printed rather than known.

        `unreported_days` is the same argument one size down. A stretch
        wide enough to matter raised during the walk; what survives to
        here is the ordinary weekend, and printing it is what makes the
        difference between "three" and "nine" a thing anybody notices.
        """
        return pd.DataFrame(
            [
                {
                    "fold": f.index,
                    "test_start": f.test.start,
                    "test_end": f.test.end,
                    "first_session": (
                        f.oos_returns.index[0] if f.sessions else pd.NaT
                    ),
                    "last_session": (
                        f.oos_returns.index[-1] if f.sessions else pd.NaT
                    ),
                    "sessions": f.sessions,
                    "anchor_dropped": f.anchor_session_dropped,
                    "unreported_days": f.unreported_days,
                }
                for f in self.folds
            ]
        )

    # -- headline -------------------------------------------------------

    @property
    def search_disclosure(self) -> str:
        """What the ledger was told about how wide the search was."""
        per_fold = {len(f.evaluated) for f in self.folds}
        if per_fold == {1}:
            return (
                f"{len(self.folds)} refit(s) each declared exactly one "
                "configuration. Either nothing was searched, or the search was "
                "not declared — a fit that sweeps a grid and returns only its "
                "winner leaves the trial ledger counting one."
            )
        return (
            f"{self.configs_evaluated} configuration(s) evaluated across "
            f"{len(self.folds)} refit(s), "
            f"{min(per_fold)}-{max(per_fold)} per refit; all written to the "
            "trial ledger."
        )

    def performance(self, **kwargs: Any) -> metrics.PerformanceReport:
        """Measure the stitched out-of-sample curve, and nothing else.

        The trial counter this run wrote to is passed through by default,
        so the deflated Sharpe sees the configurations the walk-forward
        actually spent rather than a number typed in by hand.
        """
        kwargs.setdefault("trials", self._counter)
        return metrics.evaluate(self.oos_equity, **kwargs)

    def summary(self) -> pd.DataFrame:
        """One typed row, so runs stack and compare.

        `oos_start` is the first session of the out-of-sample PERIOD, and
        not the first point of the curve, which is a different date when
        fold zero's run handed back a lead-in bar. The two were the same
        column once and the arithmetic never cared — a lead-in bar is a
        base level contributing no return — but the row exists to be
        compared period against period, and a reader who differences
        `oos_start` and `oos_end`, or filters a stack of runs on it, gets
        a period that starts before the model was refitted. The base
        level is not lost: it is `curve_base` beside it, and naming the
        two separately is what stops "the curve opens here" and "the
        out-of-sample begins here" from being quietly the same claim.
        """
        eq = self.oos_equity
        in_period = (
            eq.index[eq.index >= self.folds[0].test.start]
            if len(eq) and self.folds
            else eq.index[:0]
        )
        row = {
            "label": self.label,
            "folds": len(self.folds),
            "refit_frequency_years": self.schedule.refit_frequency,
            "min_train_years": self.schedule.min_train_years,
            "sample_start": self.schedule.start,
            "sample_end": self.schedule.end,
            "curve_base": eq.index[0] if len(eq) else pd.NaT,
            "oos_start": in_period[0] if len(in_period) else pd.NaT,
            "oos_end": eq.index[-1] if len(eq) else pd.NaT,
            "oos_sessions": int(max(len(eq) - 1, 0)),
            "seam_sessions_dropped": self.seam_sessions_dropped,
            "configs_evaluated": self.configs_evaluated,
            "trials_recorded": self.trials_recorded,
            "distinct_trials_in_ledger": (
                self._counter.distinct_count() if self._counter else None
            ),
            "in_sample_available": self._in_sample is not None,
            "search_disclosure": self.search_disclosure,
        }
        return pd.DataFrame([row])


# -- the schedule --------------------------------------------------------


@dataclass(frozen=True)
class WalkForward:
    """An expanding-window walk-forward schedule, and the walk itself.

    Construction is pure arithmetic on dates and touches no data, so a
    schedule can be printed and argued with before anything is run —
    which is the right order, since the answer to "where should the first
    refit be?" must not depend on what the first refit produced.

    `refit_frequency` and `min_train_years` are both in YEARS.
    """

    start: pd.Timestamp
    end: pd.Timestamp
    refit_frequency: int = 1
    min_train_years: int = 5

    def __post_init__(self) -> None:
        object.__setattr__(self, "start", _timestamp(self.start))
        object.__setattr__(self, "end", _timestamp(self.end))
        object.__setattr__(self, "refit_frequency", int(self.refit_frequency))
        object.__setattr__(self, "min_train_years", int(self.min_train_years))

        if self.end <= self.start:
            raise WalkForwardError(
                f"sample ends {self.end.date()} on or before it starts "
                f"{self.start.date()}"
            )
        if self.refit_frequency < MIN_REFIT_FREQUENCY_YEARS:
            raise WalkForwardError(
                f"refit_frequency is {self.refit_frequency} years; the floor "
                f"is {MIN_REFIT_FREQUENCY_YEARS}. A strategy refitted more "
                "often than annually is fitted to noise — each refit sees "
                "mostly the same history plus a sliver of new tape, and the "
                "parameter it picks tracks the sliver. This is a prior fixed "
                "before any result existed, not a finding."
            )
        if self.refit_frequency > MAX_REFIT_FREQUENCY_YEARS:
            raise WalkForwardError(
                f"refit_frequency is {self.refit_frequency} — this argument is "
                "in YEARS, not months. If you meant to refit annually, pass 1."
            )
        if self.min_train_years < 1:
            raise WalkForwardError(
                "min_train_years must be at least 1; a model fitted on less "
                "than a year of history has not seen a full seasonal cycle, "
                "let alone a bad one"
            )
        first = self.start + pd.DateOffset(years=self.min_train_years)
        if first > self.end:
            raise WalkForwardError(
                f"{self.start.date()}..{self.end.date()} is "
                f"{(self.end - self.start).days / metrics.DAYS_PER_YEAR:.1f} "
                f"years, and min_train_years={self.min_train_years} puts the "
                f"first refit at {first.date()} — after the sample ends. "
                "There is no out-of-sample period here at all."
            )

    # -- the folds -------------------------------------------------------

    def folds(self) -> tuple[Fold, ...]:
        """The ordered (train, test) pairs. Training always expands.

        Test windows tile the post-training sample exactly: each one
        starts the day after the last one ended, and the final one runs
        to `end`. Nothing is dropped in the middle and nothing overlaps,
        which is what lets the pieces be stitched into one series later
        without a day being counted twice or not at all.
        """
        refits = self._refit_dates()
        folds: list[Fold] = []
        for k, refit in enumerate(refits):
            last = k == len(refits) - 1
            test_end = self.end if last else refits[k + 1] - pd.Timedelta(days=1)
            folds.append(
                Fold(
                    index=k,
                    refit_on=refit,
                    # Expanding, every time: the window opens at the start
                    # of the sample and never at `refit - N years`.
                    train=Window(self.start, refit - pd.Timedelta(days=1)),
                    test=Window(refit, test_end),
                )
            )

        assert all(f.train.start == self.start for f in folds), "training rolled"
        assert all(
            a.test.end < b.test.start for a, b in zip(folds, folds[1:])
        ), "test windows overlap"
        return tuple(folds)

    def _refit_dates(self) -> tuple[pd.Timestamp, ...]:
        dates: list[pd.Timestamp] = []
        when = self.start + pd.DateOffset(years=self.min_train_years)
        while when <= self.end:
            dates.append(pd.Timestamp(when))
            when = when + pd.DateOffset(years=self.refit_frequency)

        # A runt tail gets absorbed by the fold before it rather than
        # earning a refit of its own. See MIN_TAIL_DAYS. Never applied to
        # the only refit there is: a short single fold is a short walk
        # forward, and deleting it would leave a schedule with no
        # out-of-sample period while reporting no error.
        if len(dates) > 1 and (self.end - dates[-1]).days < MIN_TAIL_DAYS:
            dates.pop()
        return tuple(dates)

    def schedule_frame(self) -> pd.DataFrame:
        """The plan, before anything has been run against it."""
        return pd.DataFrame(
            [
                {
                    "fold": f.index,
                    "refit_on": f.refit_on,
                    "train_start": f.train.start,
                    "train_end": f.train.end,
                    "train_years": f.train.years,
                    "test_start": f.test.start,
                    "test_end": f.test.end,
                    "test_years": f.test.years,
                }
                for f in self.folds()
            ]
        )

    # -- the walk ---------------------------------------------------------

    def run(
        self,
        *,
        fit: FitFn,
        run_fold: RunFn,
        trials: metrics.TrialCounter,
        label: str,
        include_in_sample: bool = False,
    ) -> WalkForwardResult:
        """Refit at each date, trade forward, and stitch what was traded.

        `fit(train_window)` returns either a mapping of parameters or a
        `FitOutcome` listing everything it evaluated. `run_fold(params,
        window)` returns a NAV curve for that window — a Series, a frame
        with a NAV column, or anything carrying an `.equity` attribute,
        which is how a `BacktestResult` is accepted without this module
        importing the engine.

        `trials` is required and there is no default. A walk-forward
        whose configurations went unrecorded produces a Sharpe with an
        unknowable denominator, and the whole apparatus in `metrics`
        exists to refuse that. Pointing the counter at a throwaway path
        is the same as not counting; the real ledger is committed for
        exactly that reason.

        `label` names the strategy in the ledger and enters every config
        hash, so two strategies that happen to share a parameter dict are
        two configurations rather than one.
        """
        if not isinstance(trials, metrics.TrialCounter):
            raise WalkForwardError(
                "trials must be a metrics.TrialCounter — an int cannot be "
                "appended to, and a walk-forward's whole problem is that the "
                "count is not known until the walk is over"
            )
        if not label or not label.strip():
            raise WalkForwardError(
                "label is required: an unlabelled row in the trial ledger "
                "raises the hurdle for everything after it and tells nobody why"
            )
        label = label.strip()

        folds = self.folds()
        settings = self._config_settings()

        results: list[FoldResult] = []
        pieces: list[pd.Series] = []
        in_sample: dict[int, pd.Series] = {}
        running: float | None = None
        recorded = 0
        evaluated_keys: set[str] = set()
        dropped = 0

        for fold in folds:
            outcome = _as_fit_outcome(fit(fold.train), fold)

            # Recorded BEFORE the fold is run, so a walk that dies
            # halfway still leaves behind the count of what it spent.
            # A search whose failures go unrecorded is a search that
            # only ever counts the configurations that worked.
            for candidate in outcome.evaluated:
                payload = {
                    "label": label,
                    "walk_forward": settings,
                    "params": dict(candidate),
                }
                chosen = candidate is outcome.chosen or (
                    metrics.TrialCounter.hash_config(dict(candidate))
                    == metrics.TrialCounter.hash_config(dict(outcome.chosen))
                )
                trials.record(
                    config=payload,
                    description=(
                        f"{label}: walk-forward fold {fold.index} refit "
                        f"{fold.refit_on.date()} "
                        f"({'chosen' if chosen else 'candidate'}) {dict(candidate)}"
                    ),
                    # The refit date, not the wall clock. Re-running the
                    # same walk-forward must append the same rows, or the
                    # ledger records how often we pressed go rather than
                    # how many configurations were tried.
                    timestamp=fold.refit_on.date(),
                )
                recorded += 1
                evaluated_keys.add(metrics.TrialCounter.hash_config(payload))

            curve = _to_curve(run_fold(outcome.chosen, fold.test), fold, "test")
            returns, anchor_index, anchor_value, spent, unreported = _fold_returns(
                curve, fold
            )

            if running is None:
                # The first anchor is the curve's t0 and is kept: a NAV
                # series needs a point before its first return or the
                # first day's move has nothing to be a move from.
                running = anchor_value
                pieces.append(
                    pd.Series([anchor_value], index=[anchor_index], dtype="float64")
                )
            elif spent:
                dropped += 1

            level = running * (1.0 + returns).cumprod()
            pieces.append(level)
            running = float(level.iloc[-1]) if len(level) else running

            if include_in_sample:
                in_sample[fold.index] = _to_curve(
                    run_fold(outcome.chosen, fold.train), fold, "train"
                )

            results.append(
                FoldResult(
                    index=fold.index,
                    refit_on=fold.refit_on,
                    train=fold.train,
                    test=fold.test,
                    parameters=dict(outcome.chosen),
                    evaluated=outcome.evaluated,
                    note=outcome.note,
                    raw_curve=curve,
                    oos_returns=returns,
                    anchor_session_dropped=bool(spent and fold.index > 0),
                    unreported_days=unreported,
                )
            )

        oos = pd.concat(pieces)
        oos.name = "nav"
        oos.index = pd.DatetimeIndex(oos.index, name="date")
        if not oos.index.is_monotonic_increasing or oos.index.has_duplicates:
            raise WalkForwardError(
                "the stitched out-of-sample curve is not a clean series; "
                "some fold returned dates another fold had already claimed"
            )

        return WalkForwardResult(
            label=label,
            schedule=self,
            folds=tuple(results),
            oos_equity=oos,
            trials_recorded=recorded,
            configs_evaluated=len(evaluated_keys),
            seam_sessions_dropped=dropped,
            _counter=trials,
            _in_sample=in_sample if include_in_sample else None,
        )

    def _config_settings(self) -> dict[str, Any]:
        """The part of a trial's identity that belongs to the schedule.

        The sample bounds are in here alongside the cadence, and that is
        deliberate. The same parameters walked over a longer sample are a
        different backtest, and extending the sample until the number
        improves is a search like any other — one that would otherwise
        cost nothing in the denominator.
        """
        return {
            "start": self.start.date().isoformat(),
            "end": self.end.date().isoformat(),
            "refit_frequency_years": self.refit_frequency,
            "min_train_years": self.min_train_years,
            "training": "expanding",
        }

    def __repr__(self) -> str:
        return (
            f"WalkForward({self.start.date()}..{self.end.date()}, "
            f"refit every {self.refit_frequency}y, "
            f"min_train={self.min_train_years}y, "
            f"{len(self.folds())} folds)"
        )


# -- stitching -----------------------------------------------------------


def _to_curve(raw: Any, fold: Fold, which: str) -> pd.Series:
    """Normalise whatever the run handed back into a NAV series.

    The `.equity` unwrap is how a `BacktestResult` is accepted without
    this module importing the engine. Duck typing here is not laziness —
    an import would tie the validation layer to one simulator, and the
    point of taking callables was that it should not be.
    """
    obj = getattr(raw, "equity", raw)
    try:
        curve = metrics.as_equity(obj)
    except metrics.MetricsError as exc:
        raise WalkForwardError(
            f"fold {fold.index} {which} run returned something that is not a "
            f"NAV curve: {exc}"
        ) from exc
    if len(curve) == 0:
        raise WalkForwardError(
            f"fold {fold.index} {which} run returned an empty curve for "
            f"{getattr(fold, which)}"
        )
    return curve


def _fold_returns(
    curve: pd.Series, fold: Fold
) -> tuple[pd.Series, pd.Timestamp, float, bool, int]:
    """One fold's contribution: its returns, and the anchor they run from.

    Returns are chained rather than levels concatenated, because each
    fold's run starts its own book at its own starting cash and the
    absolute NAVs are therefore not comparable across folds. Chaining the
    returns is the only join that does not invent a jump at the seam.

    A run is allowed to hand back a few bars BEFORE its test window; the
    last of them becomes the anchor, and the whole test window then makes
    it into the stitched curve. Without a lead-in the fold's own first
    session has to serve as the anchor, and that session is spent — it
    contributes no return to anybody, because the return from the end of
    the previous fold to here would span two different books. The caller
    is told how many sessions went that way rather than left to notice
    that T is short.

    The window has to be COVERED, not merely touched. A run that hands
    back the first fortnight of a year and stops has answered the
    question for a fortnight, and the stitched curve would carry the hole
    into every statistic computed from it without a column anywhere
    saying the period was short. See MAX_UNREPORTED_DAYS for why that
    raises instead.
    """
    after = curve.loc[curve.index > fold.test.end]
    if len(after):
        raise WalkForwardError(
            f"fold {fold.index} returned {len(after)} session(s) after its "
            f"test window closed on {fold.test.end.date()}, the first on "
            f"{after.index[0].date()}. A run that overruns its window has "
            "traded days a later model was fitted on."
        )

    before = curve.loc[curve.index < fold.test.start]
    inside = curve.loc[curve.index >= fold.test.start]
    if len(before) > MAX_LEAD_IN_SESSIONS:
        raise WalkForwardError(
            f"fold {fold.index} returned {len(before)} session(s) before its "
            f"test window opened on {fold.test.start.date()}. A bar or two of "
            "lead-in is the documented way to anchor the fold; this much means "
            "the run ignored the window it was handed."
        )
    if len(inside) == 0:
        raise WalkForwardError(
            f"fold {fold.index} returned nothing inside {fold.test} — the "
            "stitched curve would skip the whole period without saying so"
        )

    unreported, gap_from, gap_to = _largest_unreported_stretch(inside.index, fold)
    if unreported > MAX_UNREPORTED_DAYS:
        rate = metrics.TRADING_DAYS_PER_YEAR / metrics.DAYS_PER_YEAR
        missing = int(round(unreported * rate))
        # Stopping early and skipping a stretch lose the same tape, but
        # only one of them has anything useful to say about the
        # schedule's end date, so the closing sentence is not shared.
        if gap_to >= fold.test.end:
            tail = (
                f"The last session it returned is {inside.index[-1].date()} "
                f"and the window closes {fold.test.end.date()}. Emit the flat "
                "level, or move the schedule's end back to where the data "
                "really stops — that date is in the config hash, where a "
                "reader can see it."
            )
        else:
            tail = (
                f"It resumed afterwards and returned {len(inside)} session(s) "
                "in all, so this is a hole rather than a short fold. Emit the "
                "flat level for the days the book was doing nothing."
            )
        raise WalkForwardError(
            f"fold {fold.index} reported no session between "
            f"{gap_from.date()} and {gap_to.date()} — {unreported} calendar "
            f"days, roughly {missing} session(s) at "
            f"{metrics.TRADING_DAYS_PER_YEAR} a year — inside its test window "
            f"{fold.test}. A book that goes flat still has a NAV and still "
            "prints one; a run that stops printing has stopped reporting, and "
            "the gap would be carried into every statistic taken off the "
            "stitched curve with nothing saying the period was short. " + tail
        )

    if len(before):
        anchor_index = before.index[-1]
        anchor_value = float(before.iloc[-1])
        contributing = inside
        spent = False
    else:
        if len(inside) < 2:
            raise WalkForwardError(
                f"fold {fold.index} returned a single session and no lead-in "
                "bar, so it has no return to contribute at all"
            )
        anchor_index = inside.index[0]
        anchor_value = float(inside.iloc[0])
        contributing = inside.iloc[1:]
        spent = True

    chain = pd.concat(
        [pd.Series([anchor_value], index=[anchor_index], dtype="float64"), contributing]
    )
    returns = chain.pct_change().dropna()
    return returns, anchor_index, anchor_value, spent, unreported


def _largest_unreported_stretch(
    sessions: pd.DatetimeIndex, fold: Fold
) -> tuple[int, pd.Timestamp, pd.Timestamp]:
    """The widest run of days inside the window nobody reported.

    Bracketing the returned sessions with a sentinel one day outside each
    end of the test window collapses all three shapes of hole — a run
    that opens late, one that stops early, one that skips a stretch in
    the middle — into the same measurement, so none of them needs a rule
    of its own to be caught by, and none of them can be the one that was
    forgotten.

    Deliberately no session calendar. The fold knows dates and nothing
    else, and reaching for an exchange calendar to count the sessions
    exactly would tie a module that refuses to import a strategy to the
    assumption that everything it validates trades NYSE. Calendar days
    are the unit both ends of the comparison already speak.

    The returned dates bound the offending stretch and are only
    meaningful when the count is positive; a fold with no gap at all
    hands back a pair that reads backwards.
    """
    day = pd.Timedelta(days=1)
    marks = pd.DatetimeIndex(
        [fold.test.start - day, *sessions, fold.test.end + day]
    )
    gaps = np.diff(marks.to_numpy()).astype("timedelta64[D]").astype(np.int64) - 1
    widest = int(np.argmax(gaps))
    return int(gaps[widest]), marks[widest] + day, marks[widest + 1] - day


def _as_fit_outcome(raw: Any, fold: Fold) -> FitOutcome:
    """Accept a bare mapping, and take it at its word as one trial."""
    if isinstance(raw, FitOutcome):
        return raw
    if isinstance(raw, Mapping):
        return FitOutcome(chosen=dict(raw), evaluated=(dict(raw),))
    raise WalkForwardError(
        f"fit returned {type(raw)!r} at fold {fold.index}; expected a mapping "
        "of parameters, or a FitOutcome if more than one configuration was "
        "evaluated"
    )


# -- small helpers -------------------------------------------------------


def _timestamp(value: Any) -> pd.Timestamp:
    if isinstance(value, pd.Timestamp):
        return value.normalize()
    if isinstance(value, (datetime, date, str, np.datetime64)):
        return pd.Timestamp(value).normalize()
    raise WalkForwardError(f"expected a date, got {value!r}")


def _is_number(value: Any) -> bool:
    return isinstance(value, (int, float, np.integer, np.floating)) and not isinstance(
        value, bool
    )


def _stable_key(value: Any) -> str:
    """A comparable identity for a parameter value of any shape.

    `default=str` rather than a refusal: a parameter can legitimately be
    a tuple of bands or a callable's name, and a drift table that raised
    on the interesting cases would only ever describe the boring ones.
    """
    return json.dumps(value, sort_keys=True, default=str)


def _drift_note(
    values: Sequence[Any],
    keys: Sequence[str],
    changes: int,
    refits: int,
    spread: float,
    unstable: bool,
) -> str:
    if refits == 0:
        return "no refits"
    if len(set(keys)) == 1:
        return f"held at {values[0]!r} at every one of {refits} refit(s)"
    stem = (
        f"{len(set(keys))} distinct value(s) over {refits} refits, changing at "
        f"{changes} of them"
    )
    if not unstable:
        return f"{stem}; within the stability priors"
    if np.isfinite(spread) and spread > UNSTABLE_SPREAD:
        return (
            f"{stem}; largest choice is {spread:.1f}x the smallest, so the "
            "stitched curve is an average of materially different strategies"
        )
    return (
        f"{stem}; changing at more than half the refits is a parameter "
        "chasing the most recent year rather than one being estimated"
    )
